# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: root
  password: password

development:
  <<: *default
  database: my_app_development

test:
  <<: *default
  database: my_app_test

production:
  <<: *default
  database: stardomdb
  username: stardomdb_user
  host: dpg-cojhdeud3nmc73bqt7e0-a
  password: <%= ENV["MY_APP_DATABASE_PASSWORD"] %>
